insert into CinemaSession (filmName, sessionDate) values ('Batman', '2016-04-02 06:00:00')
insert into Seat (booked, cinemaSessionID, price, seatNumber) values (FALSE, 1, 10, 1)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 2)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 3)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 4)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 5)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 6)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 7)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 8)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 9)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 1, 10, 10)

insert into CinemaSession (filmName, sessionDate) values ('DeadPoll', '2016-04-02 08:00:00')
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 1)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 2)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 3)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 4)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 5)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 6)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 7)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 8)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 9)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 2, 10, 10)

insert into CinemaSession (filmName, sessionDate) values ('Batmanishka', '2016-04-03 08:00:00')
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 1)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 2)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 3)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 4)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 5)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 6)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 7)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 8)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 9)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 3, 15, 10)

insert into CinemaSession (filmName, sessionDate) values ('DeadPollishka', '2016-04-03 08:00:00')
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 1)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 2)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 3)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 4)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 5)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 6)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 7)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 8)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 9)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 4, 15, 10)

insert into CinemaSession (filmName, sessionDate) values ('DeadPollishka', '2016-04-03 08:00:00')
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 1)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 2)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 3)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 4)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 5)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 6)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 7)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 8)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 9)
insert into Seat (booked, cinemaSessionID, price, seatNumber ) values (FALSE, 5, 15, 10)