insert into CinemaSession (filmName, sessionDate, cinemaSessionID) values ('Batman', '02-APR-16 06.00.00.000000000 PM', session_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 1, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 2, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 3, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 4, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 5, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 6, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 7, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 8, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 9, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 1, 10, 10, seat_seq.nextval)

insert into CinemaSession (filmName, sessionDate, cinemaSessionID) values ('DeadPoll', '02-APR-16 08.00.00.000000000 PM', session_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 1, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 2, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 3, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 4, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 5, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 6, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 7, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 8, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 9, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 2, 10, 10, seat_seq.nextval)

insert into CinemaSession (filmName, sessionDate, cinemaSessionID) values ('Batmanishka', '03-APR-16 06.00.00.000000000 PM', session_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 1, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 2, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 3, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 4, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 5, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 6, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 7, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 8, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 9, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 3, 15, 10, seat_seq.nextval)

insert into CinemaSession (filmName, sessionDate, cinemaSessionID) values ('DeadPollishka', '03-APR-16 08.00.00.000000000 PM', session_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 1, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 2, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 3, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 4, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 5, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 6, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 7, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 8, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 9, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 4, 10, 10, seat_seq.nextval)

insert into CinemaSession (filmName, sessionDate, cinemaSessionID) values ('Pechenka', '03-APR-16 10.00.00.000000000 PM', session_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 1, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 2, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 3, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 4, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 5, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 6, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 7, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 8, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 9, seat_seq.nextval)
insert into Seat (bookID, booked, cinemaSessionID, price, seatNumber, seatID) values (null, 0, 5, 20, 10, seat_seq.nextval)