CREATE TABLE EMPLOYEE (
  EMPLOYEEID    NUMBER(10)    NOT NULL,
  POSITION  VARCHAR2(50)  NOT NULL,
  EMPLOYEESTATUS  NUMBER(10)  NOT NULL,
  STREET  VARCHAR2(50)  NOT NULL,
  EMPLOYEEPERSONALINFOID    NUMBER(10)    NOT NULL,
  UNITID    NUMBER(10)    NOT NULL,
  CITY  VARCHAR2(50)  NOT NULL);

ALTER TABLE EMPLOYEE ADD (
  CONSTRAINT emp_pk PRIMARY KEY (EMPLOYEEID));

CREATE SEQUENCE emp_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
CREATE OR REPLACE TRIGGER emp_bir
  BEFORE INSERT ON EMPLOYEE
  FOR EACH ROW
BEGIN
  :new.EMPLOYEEID := emp_seq.nextval;
END;
----------------------------------------------
CREATE TABLE EMPLOYEEPERSONALINFO (
  EMPLOYEEPERSONALINFOID    NUMBER(10)    NOT NULL,
  EMPLOYEENAME  VARCHAR2(50)  NOT NULL,
  AGE  NUMBER(10)  NOT NULL,
  EMPLOYEEID    NUMBER(10)    NOT NULL);

ALTER TABLE EMPLOYEEPERSONALINFO ADD (
  CONSTRAINT empInfo_pk PRIMARY KEY (EMPLOYEEPERSONALINFO));

CREATE SEQUENCE empInfo_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
CREATE OR REPLACE TRIGGER empInfo_bir
  BEFORE INSERT ON EMPLOYEEPERSONALINFO
  FOR EACH ROW
BEGIN
  :new.EMPLOYEEPERSONALINFO := empInfo_seq.nextval;
END;
--------------------------------------------------------
CREATE TABLE PROJECTS (
  PROJECTID    NUMBER(10)    NOT NULL,
  PROJECTNAME  VARCHAR2(50)  NOT NULL);

ALTER TABLE PROJECTS ADD (
  CONSTRAINT proj_pk PRIMARY KEY (PROJECTID));

CREATE SEQUENCE proj_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
CREATE OR REPLACE TRIGGER proj_bir
  BEFORE INSERT ON PROJECTS
  FOR EACH ROW
BEGIN
  :new.PROJECTID := proj_seq.nextval;
END;
-------------------------------------------------------
CREATE TABLE EMPLOYEE_PROJECT (
  PROJECTID    NUMBER(10)    NOT NULL,
  EMPLOYEEID  NUMBER(10)   NOT NULL);
--------------------------------------------------------
CREATE TABLE UNIT (
  UNITID    NUMBER(10)    NOT NULL,
  UNITNAME  VARCHAR2(50)  NOT NULL);

ALTER TABLE UNIT ADD (
  CONSTRAINT unit_pk PRIMARY KEY (UNITID));

CREATE SEQUENCE unit_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
CREATE OR REPLACE TRIGGER unit_bir
  BEFORE INSERT ON UNIT
  FOR EACH ROW
BEGIN
  :new.UNITID := proj_seq.nextval;
END;

